---

loopback: 10.255.0.6/32

bgp_fabric:
  asn: 65004
  router_id: 10.255.0.6
  neighbor:
    - {address: 10.0.255.25, remote_as: 65000}
    - {address: 10.0.255.29, remote_as: 65000}
  networks:
    - 10.255.0.6/32
    - 10.0.255.24/30
    - 10.0.255.28/30

interfaces:
  Ethernet1:
    alias: uplink-spine-1
    port_state: no switchport
    address: 10.0.255.26/30
  Ethernet2:
    alias: uplink-spine-2
    port_state: no switchport
    address: 10.0.255.30/30
  Ethernet3:
    alias: peerlink-leaf-3
