---

loopback: 10.255.0.5/32

bgp_fabric:
  asn: 65003
  router_id: 10.255.0.5
  neighbor:
    - {address: 10.0.255.17, remote_as: 65000}
    - {address: 10.0.255.21, remote_as: 65000}
  networks:
    - 10.255.0.5/32
    - 10.0.255.16/30
    - 10.0.255.20/30

interfaces:
  Ethernet1:
    alias: uplink-spine-1
    port_state: no switchport
    address: 10.0.255.18/30
  Ethernet2:
    alias: uplink-spine-2
    port_state: no switchport
    address: 10.0.255.22/30
  Ethernet3:
    alias: peerlink-leaf-4
