---

loopback: 10.255.0.1/32

bgp_fabric:
  asn: 65000
  router_id: 10.255.0.1
  neighbor:
    - {address: 10.0.255.2, remote_as: 65001}
    - {address: 10.0.255.10, remote_as: 65002}
    - {address: 10.0.255.18, remote_as: 65003}
    - {address: 10.0.255.26, remote_as: 65004}
    - {address: 10.0.255.34, remote_as: 65005}
    - {address: 10.0.255.42, remote_as: 65006}
  networks:
    - 10.255.0.1/32

interfaces:
  Ethernet1:
    alias: downlink-leaf-1
    port_state: no switchport
    address: 10.0.255.1/30
  Ethernet2:
    alias: downlink-leaf-2
    port_state: no switchport
    address: 10.0.255.9/30
  Ethernet3:
    alias: downlink-leaf-3
    port_state: no switchport
    address: 10.0.255.17/30
  Ethernet4:
    alias: downlink-leaf-4
    port_state: no switchport
    address: 10.0.255.25/30
  Ethernet5:
    alias: downlink-leaf-5
    port_state: no switchport
    address: 10.0.255.33/30
  Ethernet6:
    alias: downlink-leaf-6
    port_state: no switchport
    address: 10.0.255.41/30

